### ISSUE TITLE
Add Donate Button

### ISSUE THREAD

**Issue by lexman02** [ArchoNetwork/ArchonSite_BETA#3]
For donate ranks on Discord.

**MAYBE** (Cancel Button)

**Comment by Crewdz** [comment]
I highly agree with both actually. It gives people power to cancel if they don't know how...
    The donation button for the VIP ranks should be included.

**Comment by lexman02** [comment]
Similar Issue https://github.com/ArchoNetwork/ArchonSite/issues/6
