### ISSUE TITLE
Archon Schools/First Student

### ISSUE THREAD

**Issue by lexman02** [ArchoNetwork/ArchonSite_BETA#4]
![image](https://user-images.githubusercontent.com/10473497/32994563-21e575a4-cd37-11e7-920e-670178096262.png)
Make a sub-site for Archon Network Schools.  

- [ ] Basic home page
- [ ] Downloads Page (Embed?)
- [ ] Rules
- [ ] ~~Route Map?~~

**Comment by Crewdz** [comment]
Maybe exclude the Route Map. I believe they will obtain the right to produce their own. However, I do think it's necessary to have a downloads page for the general public mods they're going to use.  _Embed_
    Basic Homepage, of course.
